version: '3'
services:

  db_mysql:
    image: mysql:8.0.22
    container_name: baralga___db_mysql
    hostname: db_mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=mysql"
      - "MYSQL_DATABASE=baralga"
    ports:
      - "3306:3306"

  db_postgres:
    image: postgres
    container_name: baralga___db_postgres
    hostname: db_postgres
    environment:
      - "POSTGRES_DB=baralga"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_USER=postgres"
    ports: 
      - "5432:5432"
